### PR TITLE
Setup Material Design

### PR DESCRIPTION
**Pull request by thiagogsr**
Using the [materializecss](materializecss.com) framework and displaying the repositories using the card component.

### CODE REVIEW

**Comment by lcalmeida** [comment]
Um tempo atrás tinhamos pensado em usar inglês nos repositórios publicos. O que acha?

**Comment by thiagogsr** [comment]
@lcalmeida nos títulos e descrições dos pulls requests?

**Comment by lcalmeida** [comment]
sim. Tudo relativo aos repos públicos

**Comment by lcalmeida** [comment]
ué. sumiram os comentários

**Comment by thiagogsr** [comment]
@lcalmeida Can you speak english, please? :joy: :joy:

**Comment by lcalmeida** [comment]
Nice! This project will be very useful :+1:

**Comment by thiagogsr** [comment]
@lcalmeida I think I can merge this pull request because the material design setup is done. I will open another to display the pull requests and issues lists. WDYT?

**Comment by lcalmeida** [comment]
@thiagogsr Can you add prints to PR of how it will look like?

**Comment by lcalmeida** [comment]
:+1: :shipit:

**Comment by thiagogsr** [comment]
@lcalmeida of course, see below:

image

**Pull request merged**
